brews:
  - install: |
      bin.install "git-vertag"
      man1.install Dir.glob('git-vertag*.1')
    tap:
      owner: kyoh86
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/kyoh86/git-vertag
    description: GO GitHub project manager
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    main: ./cmd/git-vertag
    hooks:
      post:
        - go get github.com/kyoh86/git-vertag
        - make man
archives:
  - id: gzip
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
      - git-vertag*.1
