name: Test

on:
  push:
    branches: '*'

jobs:
  vendor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: get dependencies
        run: go get -v -t -d ./...
      - name: vendoring
        run: go mod vendor

      - uses: actions/upload-artifact@v2
        with:
          name: repository
          path: .

  docker:
    runs-on: ubuntu-latest
    needs: vendor
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: repository
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            ghcr.io/${{ github.repository }}:draft

  lint:
    runs-on: ubuntu-latest
    needs: vendor
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.32

  test:
    runs-on: ubuntu-latest
    needs: vendor
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - uses: actions/download-artifact@v2
        with:
          name: repository
          path: .
      - name: test race
        run: go test -v -race ./...

  release-test:
    runs-on: ubuntu-latest
    needs: vendor
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - uses: actions/download-artifact@v2
        with:
          name: repository
          path: .
      - name: release (dry-run)
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist --skip-publish --snapshot

  cover:
    runs-on: ubuntu-latest
    needs: vendor
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - uses: actions/download-artifact@v2
        with:
          name: repository
          path: .
      - name: take coverage
        run: go test -coverprofile=coverage.txt -covermode=count ./...
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.txt
